### PR TITLE
feat(playerWalletBalance): add balance field to player wallet

### PR DESCRIPTION
**Pull request by k-grant**

### CODE REVIEW

**Review by itsthetombomb — APPROVED** [review]
what unit is this balance in?

**Comment by k-grant** [comment]
> what unit is this balance in?

wei, i wonder if that should be specified in the field name... 

i think wei should probably always be used as the default so maybe not? We also aren't consistently including the unit in the field name across the board (just looking at various protos). not sure.... I could still change this down the chain in saga-protos now before I merge the actual work in. I know @axcrest mentioned the option of "InWei" in the filed name in the saga-protos PR as well.

**Comment by axcrest** [comment]
Yeah it can be confusing if we don't label it.  I suppose we could leave it here but make sure the SDK facing ones are specific.

**Comment by itsthetombomb** [comment]
> Yeah it can be confusing if we don't label it. I suppose we could leave it here but make sure the SDK facing ones are specific.

I believe the standard for our backend is wei, I know executor and nmyth is transferring / granting in wei. The decision was made to simplify the front end's work using web3's [`fromWei()` or `toWei()` methods](https://web3js.readthedocs.io/en/v1.2.11/web3-utils.html#fromwei). 

Bridge specifies the units, [look here for reference](https://github.com/MythicalGames/saga-sdk-proto/blob/develop/api/bridge/definition.proto#L24).

**Comment by k-grant** [comment]
> Yeah it can be confusing if we don't label it. I suppose we could leave it here but make sure the SDK facing ones are specific.
@axcrest 

for my own sake and clarification....  aren't these the SDK facing ones? what are the other ones?

**Comment by k-grant** [comment]
> > Yeah it can be confusing if we don't label it. I suppose we could leave it here but make sure the SDK facing ones are specific.
> > @axcrest
> 
> for my own sake and clarification.... aren't these the SDK facing ones? what are the other ones?

adjusted this just to be balance in wei and made the appropriate changes downstream as well so this question is less relevant. going to merge this

**Pull request merged**
