### PR TITLE
Make all writes async

### PR DESCRIPTION
**Pull request by erik-mythical**

### CODE REVIEW

**Review by DustinLiang — APPROVED** [review]

**Review by kwang-mythical — CHANGES_REQUESTED** [review]
the stream response needs updating to provide the appropriate response payload.

**Review by itsthetombomb — APPROVED** [review]

**Comment by erik-mythical** [comment]
Added error response and modified stream messages so that all async calls will get an indication of success or failure. Probably not the final form yet.

**Review by kwang-mythical — APPROVED** [review]
gonna need to rethink or maybe just simply update the status updates for anything quote related. The idea for the quote calls is something quick but doesn't need to be commited on. Without it being sync, the async response needs to be more dataful and return a new state, like PENDING or QUOTED.

**Comment by erik-mythical** [comment]
Yeah. I feel like this is just a first draft.

**Pull request merged**
